# Generated by Django 4.1.6 on 2023-02-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Product',
        ),
    ]
