# Generated by Django 4.1.6 on 2023-02-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_game_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('date_created',)},
        ),
    ]
