# Generated by Django 4.1.6 on 2023-02-13 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('423ba450-07d1-4498-a533-6d2aa29eede6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
