# Generated by Django 4.1.6 on 2023-03-02 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d04b21e-9e82-4c45-8274-b578a42f2428'), editable=False, primary_key=True, serialize=False),
        ),
    ]
