# Generated by Django 4.1.6 on 2023-03-02 08:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('395bfe10-8d98-46f5-aa18-240c59343823'), editable=False, primary_key=True, serialize=False),
        ),
    ]
